@authority = https://content.bioy.app/api/v1

@from = 94
@to = 95
@locale=hi
@variant=classic

###
# https://content.bioy.app/api/v1/chapter/from/93/to/95?locale=hi&story=classic
GET {{authority}}/chapter/from/{{from}}/to/{{to}}?locale={{locale}}&story={{variant}} HTTP/1.1